---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-foo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io #without adding this it will not delete the pods when the appication is deleted
spec:
  project: default
  source:
    repoURL: https://github.com/yousif609230/argocd-proj.git
    targetRevision: main
    #path: environments/staging/my-app
    path: environments/staging/my-first-app
  destination:
    server: https://kubernetes.default.svc 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
      allowEmpty: false 
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - validate=true
      - pruneLast=true