helm:
  parameters:
  - name: replicaCount
    value: "2"
    forcestring: false
  - name: image.repository
    value: yousif101/argocdproj
    forcestring: false
  - name: image.tag
    value: v0.4.3
    forcestring: true
  - name: image.name
    value: yousif101/argocdproj
    forcestring: true
